### ISSUE TITLE
KeyError: 'embeddings.position_ids'

### ISSUE THREAD

**Issue by Youssef-Barakat** [IIEleven11/StyleTTS2FineTune#10]
After finetuning my own plbert. it can't be read

**Comment by IIEleven11** [comment]
I think maybe you want to do this on the StyleTTS2 repo not mine. Would also need much more information

**Comment by Youssef-Barakat** [comment]
I think you should replace this in the util file in plbert folder to train styletts2

try:
  del new_state_dict["embeddings.position_ids"]
except KeyError:
  pass

**Comment by IIEleven11** [comment]
If you have suggestions, issues, or comments about the code I have written here, specifically the tools I am sharing, or the fine tuning process I go over for the STTS2 model I would be happy to review and discuss them.

I did not create the STTS2 model. I do not control the repository for STTS2. You're suggesting source code changes to the wrong person in the wrong place. So, again, If you want to send a PR or point out an issue I will direct you to the STTS2 repository.

**Comment by Youssef-Barakat** [comment]
yes thank you I did write here because this repo is mainly for fine-tuning and I have faced this issue while trying it, at all thank you <3
