### ISSUE TITLE
phonemizer

### ISSUE THREAD

**Issue by traderpedroso** [IIEleven11/StyleTTS2FineTune#11]
why not using with_strees=True and preserve_punctuation=True for creating dataset?

**Comment by IIEleven11** [comment]
I wasn't aware of those parameters. I just looked them up, seems helpful, have you used them yet? If so did you run into any issues or notice anything odd with the model after training?

**Comment by traderpedroso** [comment]
> I wasn't aware of those parameters. I just looked them up, seems helpful, have you used them yet? If so did you run into any issues or notice anything odd with the model after training?

In fact, I have never trained without punctuation preservation and without with_stress=True exactly for this reason. I questioned it because the two times I trained the model from scratch, it turned out well for me, so I was uncertain about inference, both in the official implementation and in libraries that support StyleTTS2, which are always with with_stress=True and preserve_punctuation=True. Since training is not inexpensive, I decided to ask.

**Comment by IIEleven11** [comment]
> > I wasn't aware of those parameters. I just looked them up, seems helpful, have you used them yet? If so did you run into any issues or notice anything odd with the model after training?
> 
> In fact, I have never trained without punctuation preservation and without with_stress=True exactly for this reason. I questioned it because the two times I trained the model from scratch, it turned out well for me, so I was uncertain about inference, both in the official implementation and in libraries that support StyleTTS2, which are always with with_stress=True and preserve_punctuation=True. Since training is not inexpensive, I decided to ask. 
> 
> I noticed that one training session turned out better than the other; the only thing I changed was the phonemizer to Deep-Phonemizer, and with Deep, the results were better, considering that I trained my Deep-Phonemizer with another dataset. Here  the [dataset](https://github.com/open-dict-data).
> 
> 
> 
> 

Deep phonemizer. I haven't heard of that one either. I'll look into it. I've been working with xttsv2 lately because like you said StyleTTS2 is not cheap to train. But I'll definitely add those parameters. Unless you want the credit you can send a PR. Thanks!
